#!/usr/bin/env python3
"""Generate Adafruit-GFX style bitmap font headers for the tag's scene renderer (epd_canvas.c).

Renders DejaVu Sans Bold glyphs monochrome (no anti-aliasing) with Pillow and
writes one C header per entry in FONT_SPECS into Firmware/src/fonts/.

Usage (from any working directory):

    python3 tools/fonts/gen_gfx_fonts.py [--font-dir DIR] [--out-dir DIR] [--check]

--check additionally decodes each font from the in-memory glyph tables, renders
a sample string the way epd_canvas_text does and saves a 3x PNG to
/tmp/gfx_font_check/ for visual inspection.
"""

import argparse
import os
import sys
from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT_DIR = REPO_ROOT / "Firmware" / "src" / "fonts"
CHECK_DIR = Path("/tmp/gfx_font_check")

DEGREE_SLOT = 0x7F
DEGREE_SIGN = "\u00b0"
CHECK_TEXT_DIGITS = "-0123456789:"
CHECK_TEXT_TEXT = "Thu 08 Oct 23\x7fC 2.98V 89%"

TTF_SOURCE_NAMES = {"DejaVuSans-Bold.ttf": "DejaVu Sans Bold"}

U8 = (0, 0xFF)
I8 = (-0x80, 0x7F)
U16 = (0, 0xFFFF)


@dataclass(frozen=True)
class FontSpec:
    c_name: str
    ttf: str
    size: int
    first: int
    last: int


FONT_SPECS = [
    FontSpec("font_digits_80", "DejaVuSans-Bold.ttf", 80, 0x2D, 0x3A),
    FontSpec("font_digits_64", "DejaVuSans-Bold.ttf", 64, 0x2D, 0x3A),
    FontSpec("font_digits_44", "DejaVuSans-Bold.ttf", 44, 0x2D, 0x3A),
    FontSpec("font_bold_22", "DejaVuSans-Bold.ttf", 22, 0x20, 0x7F),
    FontSpec("font_bold_16", "DejaVuSans-Bold.ttf", 16, 0x20, 0x7F),
    FontSpec("font_bold_12", "DejaVuSans-Bold.ttf", 12, 0x20, 0x7F),
]


@dataclass
class Glyph:
    code: int
    bitmap_offset: int
    width: int
    height: int
    x_advance: int
    x_offset: int
    y_offset: int
    data: bytes


@dataclass
class BuiltFont:
    spec: FontSpec
    glyphs: list
    bitmap: bytes
    y_advance: int


def _fit(value, limits, what):
    lo, hi = limits
    if not lo <= value <= hi:
        raise OverflowError(f"{what} = {value} does not fit in its C type [{lo}, {hi}]")
    return value


def _render_glyph(font, size, code):
    """Render one code point; return (w, h, xAdvance, xOffset, yOffset, packed bits)."""
    ch = DEGREE_SIGN if code == DEGREE_SLOT else chr(code)
    pen_x, pen_y = size, 2 * size
    img = Image.new("L", (4 * size, 4 * size), 0)
    draw = ImageDraw.Draw(img)
    draw.fontmode = "1"
    draw.text((pen_x, pen_y), ch, font=font, fill=255, anchor="ls")

    x_advance = _fit(round(font.getlength(ch)), U8, f"xAdvance[0x{code:02X}]")
    bbox = img.getbbox()
    if bbox is None:
        # No ink (space): 1x1 blank bitmap, zero offsets.
        return 1, 1, x_advance, 0, 0, b"\x00"

    left, top, right, bottom = bbox
    width, height = right - left, bottom - top
    _fit(width, U8, f"width[0x{code:02X}]")
    _fit(height, U8, f"height[0x{code:02X}]")
    x_offset = _fit(left - pen_x, I8, f"xOffset[0x{code:02X}]")
    y_offset = _fit(top - pen_y, I8, f"yOffset[0x{code:02X}]")

    pix = img.load()
    bits = bytearray((width * height + 7) // 8)
    idx = 0
    for row in range(height):
        for col in range(width):
            if pix[left + col, top + row]:
                bits[idx >> 3] |= 0x80 >> (idx & 7)
            idx += 1
    return width, height, x_advance, x_offset, y_offset, bytes(bits)


def build_font(spec, font_dir):
    ttf_path = os.path.join(font_dir, spec.ttf)
    font = ImageFont.truetype(ttf_path, spec.size)

    glyphs = []
    blob = bytearray()
    for code in range(spec.first, spec.last + 1):
        width, height, x_adv, x_off, y_off, data = _render_glyph(font, spec.size, code)
        offset = _fit(len(blob), U16, f"bitmapOffset[0x{code:02X}] in {spec.c_name}")
        glyphs.append(Glyph(code, offset, width, height, x_adv, x_off, y_off, data))
        blob += data

    ascent, descent = font.getmetrics()
    y_advance = _fit(ascent + descent, U8, f"yAdvance in {spec.c_name}")
    return BuiltFont(spec, glyphs, bytes(blob), y_advance)


def _char_comment(code):
    if code == DEGREE_SLOT:
        return "degree"
    ch = chr(code)
    if ch == "'":
        return "quote"
    if ch == "\\":
        return "backslash"
    return f"'{ch}'"


def render_header(built):
    spec = built.spec
    name = spec.c_name
    source = TTF_SOURCE_NAMES.get(spec.ttf, spec.ttf)
    out = [
        "// Generated by tools/fonts/gen_gfx_fonts.py -- do not edit.",
        f"// Source: {source}, {spec.size}px, chars 0x{spec.first:02X}-0x{spec.last:02X}. "
        "DejaVu fonts license: see tools/fonts/README.md",
        "#pragma once",
        '#include "../epd_font.h"',
        "",
        f"static const uint8_t {name}_bitmaps[] = {{",
    ]
    for g in built.glyphs:
        cmt = _char_comment(g.code)
        for i in range(0, len(g.data), 16):
            chunk = g.data[i:i + 16]
            line = "\t" + ", ".join(f"0x{b:02X}" for b in chunk) + ","
            if i == 0:
                line += f" // {cmt}"
            out.append(line)
    out += [
        "};",
        "",
        f"static const GFXglyph {name}_glyphs[] = {{",
        "\t// bitmapOffset, width, height, xAdvance, xOffset, yOffset",
    ]
    for g in built.glyphs:
        out.append(
            f"\t{{ {g.bitmap_offset}, {g.width}, {g.height}, {g.x_advance}, "
            f"{g.x_offset}, {g.y_offset} }}, // {_char_comment(g.code)}"
        )
    out += [
        "};",
        "",
        f"static const GFXfont {name} = {{",
        f"\t(uint8_t *){name}_bitmaps, (GFXglyph *){name}_glyphs, "
        f"0x{spec.first:02X}, 0x{spec.last:02X}, {built.y_advance}}};",
        "",
    ]
    return "\n".join(out)


def _decode_bit(built, glyph, row, col):
    idx = row * glyph.width + col
    byte = built.bitmap[glyph.bitmap_offset + (idx >> 3)]
    return (byte >> (7 - (idx & 7))) & 1


def render_check(built, out_path):
    """Draw a sample string from the in-memory tables, following epd_canvas_text."""
    spec = built.spec
    text = CHECK_TEXT_DIGITS if spec.c_name.startswith("font_digits_") else CHECK_TEXT_TEXT
    margin = built.y_advance
    baseline = 2 * built.y_advance
    total_adv = 0
    for ch in text:
        total_adv += built.glyphs[ord(ch) - spec.first].x_advance
    width = total_adv + 2 * margin
    height = 3 * built.y_advance

    canvas = bytearray(b"\xff" * (width * height))
    pen = margin
    for ch in text:
        code = ord(ch)
        if not spec.first <= code <= spec.last:
            raise ValueError(f"check char 0x{code:02X} outside font range")
        g = built.glyphs[code - spec.first]
        dx = pen + g.x_offset
        dy = baseline + g.y_offset
        for row in range(g.height):
            for col in range(g.width):
                if not _decode_bit(built, g, row, col):
                    continue
                x, y = dx + col, dy + row
                if not (0 <= x < width and 0 <= y < height):
                    raise ValueError(f"{spec.c_name}: glyph 0x{code:02X} clipped in check canvas")
                canvas[y * width + x] = 0
        pen += g.x_advance

    img = Image.frombytes("L", (width, height), bytes(canvas))
    img = img.resize((width * 3, height * 3), Image.NEAREST)
    img.save(out_path)
    return out_path


def default_font_dir():
    try:
        import matplotlib
    except ImportError:
        return None
    return os.path.join(matplotlib.get_data_path(), "fonts", "ttf")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--font-dir", help="directory containing DejaVuSans.ttf and DejaVuSans-Bold.ttf")
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR),
                        help="output directory for generated headers (default: Firmware/src/fonts)")
    parser.add_argument("--check", action="store_true",
                        help="also save visual self-check PNGs to /tmp/gfx_font_check/")
    args = parser.parse_args(argv)

    font_dir = args.font_dir or default_font_dir()
    if font_dir is None:
        parser.error("matplotlib is not importable; pass --font-dir DIR containing DejaVuSans-Bold.ttf")
    for spec in FONT_SPECS:
        path = os.path.join(font_dir, spec.ttf)
        if not os.path.isfile(path):
            parser.error(f"font file not found: {path}")

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    if args.check:
        CHECK_DIR.mkdir(parents=True, exist_ok=True)

    for spec in FONT_SPECS:
        built = build_font(spec, font_dir)
        header_path = out_dir / f"{spec.c_name}.h"
        header_path.write_text(render_header(built), encoding="utf-8")
        zero = next(g for g in built.glyphs if g.code == ord("0")) if spec.first <= ord("0") <= spec.last else None
        zero_h = zero.height if zero else "n/a"
        print(f"{header_path}: bitmap={len(built.bitmap)} bytes, yAdvance={built.y_advance}, "
              f"'0' height={zero_h}")
        if args.check:
            png = render_check(built, CHECK_DIR / f"{spec.c_name}.png")
            print(f"  check: {png}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
